### ISSUE TITLE
Inner for optimization

### ISSUE THREAD

**Issue by ibrahimyilmaz** [capogluuu/IEEE-GSU-ALGO-101#2]
Merhabalar,

```cpp
for (int j = 0; j < V.size()- i-1; j++)
```
Bu satir boyle olmali cunku komsu karsilastirmasi yaparken sorted olmayan en buyuk deger saga gidiyor.

https://github.com/capogluuu/IEEE-GSU-ALGO-101/blob/7381f96b5665a36ea17ba68fee62fe3a92c7360d/week2_10_11_21/BubbleSort.cpp#L27

**Comment by capogluuu** [comment]
Açtığınız issue için teşekkür ederiz. Ders kapsamında issue nedir, neden açılır gibi programlama açısından güzel sorulara, bu issue ile güzel bir yanıt oluşturabiliriz. Teşekkürler.
